### ISSUE TITLE
Implement std::error::Error for trash::Error

### ISSUE THREAD

**Issue by Heliozoa** [ArturKovacs/trash#16]
Hi,
Thanks for your work on trash. Currently, the crate's custom error type doesn't implement std::error::Error, which makes using error handling libraries with it like [anyhow](https://crates.io/crates/anyhow) or [thiserror](https://crates.io/crates/thiserror) a little awkward.
```rust
fn main() {}

fn anyhow() -> anyhow::Result<()> {
    use anyhow::Context;
    trash::remove("some file").context("context")?; // error, have to map_err to another type first
    Ok(())
}

#[derive(Debug, thiserror::Error)]
enum MyError {
    #[error("some error")]
    MyVariant,
    #[error("error trashing")] // error, cannot use #[source]
    Trash(#[source] trash::Error),
}
```
Implementing the trait should be straightforward and only require a minor version bump when released. I could write a PR for it, using the current doc comments as the Display strings.

**Comment by ArturKovacs** [comment]
Hi,

If you make a PR I'll review it and will consider it for merging. 🙂

**Comment by ArturKovacs** [comment]
It is now published on crates.io
