### ISSUE TITLE
Test CI service

### ISSUE THREAD

**Issue by ayazhafiz** [ArturKovacs/trash#2]
Would this project be interested in a CI service, like [Travis](https://travis-ci.com), to perform automated testing? It would be pretty easy to set up; just adding a `.travis.yml` and enabling the repository on the Travis website. There are other CIs (like CircleCI) available as well.

**Comment by ArturKovacs** [comment]
Thanks for opening an issue! It's a bit unfortunate that I haven't been able to answer until now but I believe that setting up a ci would certainly benefit this library.

I don't have the opportunity to do that in the near future but I'll make that happen sometime soon.

**Comment by ayazhafiz** [comment]
If you are willing to turn on Travis or CirlceCI for this repo, I would be happy to write and submit a pull request for the CI configuration!

**Comment by ArturKovacs** [comment]
Yes, you are welcome to set up a Travis config and make a PR.

**Comment by ArturKovacs** [comment]
I'm closing this as we have Azure test set up currently.
