### ISSUE TITLE
Consider renaming project to rust-trash or trash-rs

### ISSUE THREAD

**Issue by cjbassi** [ArturKovacs/trash#20]
Or something else that reflects that it's a rust library, since there's already a bunch of projects named trash. Just another small thing :)

**Comment by ArturKovacs** [comment]
The short description (i.e. "About"), the readme, and GitHub's language detection all make it abundantly clear that this is a Rust project. Usually when people are searching for a particular library to solve a task they have, they direct their search towards a particular programing language or set of programing languages. Image if you were looking for a library on `crates.io` and every single crate had `rs` or `rust` in its name. It adds no information but it takes up space.

I'm closing this as I don't think your argument is strong enough to change the name but let me know if I missed something.

**Comment by cjbassi** [comment]
The name change would only be for the github project name, not on crates.io. Just to help distinguish the crate on github. Example of this: https://github.com/whitequark/rust-xdg

**Comment by ArturKovacs** [comment]
I see. I did rename it as it might help cloning to a local folder with another similarly named repo already present.

You might need to update your remote URL

**Comment by cjbassi** [comment]
That's great, thanks.
