### ISSUE TITLE
Help with MacOS support for Version 2.

### ISSUE THREAD

**Issue by ArturKovacs** [ArturKovacs/trash#4]
MacOS support is essential for this library but unfortunately I don't have a Mac.

This issue is a call for developers to help implementing a new and more complete version of this library. This work is currently in progress on the `v2-dev` branch. All the functionality intended for version 2 is already implemented for Windows and a Linux implementation is currently in the making on the `v2-linux` branch. 

```
              ____  ____  ________  _____     _______    
             |_   ||   _||_   __  ||_   _|   |_   __ \  
               | |__| |    | |_ \_|  | |       | |__) | 
               |  __  |    |  _| _   | |   _   |  ___/  
              _| |  | |_  _| |__/ | _| |__/ | _| |_     
 ____      __|____||____||________||________||_____|_____  ______    
|_  _|    |_  _|/ \     |_   \|_   _||  _   _  ||_   __  ||_   _ `.  
  \ \  /\  / / / _ \      |   \ | |  |_/ | | \_|  | |_ \_|  | | `. \ 
   \ \/  \/ / / ___ \     | |\ \| |      | |      |  _| _   | |  | | 
    \  /\  /_/ /   \ \_  _| |_\   |_    _| |_    _| |__/ | _| |_.' / 
     \/  \/|____| |____||_____|\____|  |_____|  |________||______.'  
```

Text to ASCII Art: http://patorjk.com/software/taag/#p=display&f=Varsity&t=%20%20%20%20%20%20%20%20%20%20%20%20%20HELP%0AWANTED

**Comment by ArturKovacs** [comment]
@ayazhafiz would you be interested in this?

**Comment by ayazhafiz** [comment]
Yes, I can help with this.

**Comment by ArturKovacs** [comment]
Closing this due to #8.
